- name: Configure instance(s)
  hosts: wsserver
  tasks:
    - name: Install IIS (Web-Server only)
      win_feature:
        name: Web-Server
        state: present

    - name: Install IIS (Web-Server and Web-Common-Http)
      win_feature:
        name:
          - Web-Server
          - Web-Common-Http
        state: present

    - name: Install IIS Web-Server with sub features and management tools
      win_feature:
        name: Web-Server
        state: present
        include_sub_features: true
        include_management_tools: true
        register: win_feature

    - name: Copy index text page
      win_copy:
        src: "MobEAD/index.html"
        dest: "C:\\inetpub\\wwwroot\\index.html"